---

  logging:
    level:
      org.springframework: INFO

  server:
    port: 9080

  spring:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://ml-supply-1.sandbox/arbina-sps
      username: arbina-sps
      password: dosqYGnd
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: update
    jackson:
      serialization:
        indentOutput: true
    security:
      oauth2:
        resource:
          jwk:
            keySetUri: https://sso.arbina.com/.well-known/jwks.json

  arbina:
    infra:
      oauth:
        server: https://sso.arbina.com
        client-id: sandbox_infra
        client-secret: CvdOBKw5eYIo
    swagger:
      oauth:
        client-id: clientNoSecret
        client-secret:
        server: https://sso.arbina.com